import type { PracticeHistory } from '../types';

/**
 * Generate a formatted text report for a single practice result
 */
export function generateResultReport(entry: PracticeHistory): string {
  const { session, feedback, date } = entry;
  const timeMin = Math.floor(session.timeUsed / 60);
  const timeSec = session.timeUsed % 60;

  let report = '';
  report += '═══════════════════════════════════════════\n';
  report += '  CELPIP WRITING PRACTICE - RESULT REPORT\n';
  report += '═══════════════════════════════════════════\n\n';
  report += `Date: ${date}\n`;
  report += `Task: ${session.taskType === 'task1' ? 'Task 1 - Email Writing' : 'Task 2 - Survey Response'}\n`;
  report += `Question: ${session.question.title}\n`;
  report += `Word Count: ${session.wordCount}\n`;
  report += `Time Used: ${timeMin}m ${timeSec}s\n\n`;

  report += '───────────────────────────────────────────\n';
  report += '  QUESTION PROMPT\n';
  report += '───────────────────────────────────────────\n\n';
  report += session.question.prompt + '\n\n';

  report += '───────────────────────────────────────────\n';
  report += '  YOUR RESPONSE\n';
  report += '───────────────────────────────────────────\n\n';
  report += session.text + '\n\n';

  if (feedback) {
    report += '───────────────────────────────────────────\n';
    report += '  AI FEEDBACK & SCORES\n';
    report += '───────────────────────────────────────────\n\n';
    report += `Overall Score: ${feedback.overallScore}/12\n\n`;

    for (const cat of feedback.categories) {
      report += `${cat.name}: ${cat.score}/12\n`;
      report += `  ${cat.feedback}\n\n`;
    }

    if (feedback.suggestions.length > 0) {
      report += '───────────────────────────────────────────\n';
      report += '  SUGGESTIONS FOR IMPROVEMENT\n';
      report += '───────────────────────────────────────────\n\n';
      feedback.suggestions.forEach((s, i) => {
        report += `${i + 1}. ${s}\n`;
      });
      report += '\n';
    }
  }

  report += '═══════════════════════════════════════════\n';
  report += '  Generated by CELPIP Writing Practice App\n';
  report += '═══════════════════════════════════════════\n';

  return report;
}

/**
 * Download text content as a file
 */
export function downloadTextFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Download JSON content as a file
 */
export function downloadJsonFile(data: unknown, filename: string): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generate filename for a result export
 */
export function getResultFilename(entry: PracticeHistory): string {
  const taskLabel = entry.session.taskType === 'task1' ? 'Task1_Email' : 'Task2_Survey';
  const date = new Date().toISOString().split('T')[0];
  return `CELPIP_${taskLabel}_${date}.txt`;
}
